import mongoose from "mongoose";
const Schema = mongoose.Schema;
const addressSchema = mongoose.Schema({
  pincode: {
    type: String,
    required: false,
    trim: true,
    default: "",
    min: 6,
    max: 6,
  },
  city: { type: String, required: false, trim: true, default: "" },
  state: { type: String, required: false, trim: true, default: "" },
  country: { type: String, required: false, trim: true, default: "" },
  address1: { type: String, required: false, trim: true, default: "" },
  address2: { type: String, required: false, trim: true, default: "" },
  landmark: { type: String, required: false, trim: true, default: "" },
});
const VenueUserSchema = new Schema(
  {
    name: { type: String, required: false, trim: true, default: "" },
    company_name: { type: String, required: false, trim: true, default: "" },
    contactPhone: {
      type: String,
      required: true,
      trim: true,
      unique: true,
      default: "",
    },
    contactEmail: { type: String, required: false, trim: true, default: "" },
    zipcode: {
      type: String,
      required: false,
      trim: true,
      default: "",
      min: 6,
      max: 6,
    },
    city: { type: String, required: false, trim: true, default: "" },
    state: { type: String, required: false, trim: true, default: "" },
    country: { type: String, required: false, trim: true, default: "" },
    address: { type: String, required: false, trim: true, default: "" },
    mainImage: { type: String, required: false, trim: false, default: "" },
    category: { type: String, required: false, trim: true, default: "" },
    description: { type: String, required: false, trim: true, default: "" },
    price: { type: Number, required: false, trim: true, default: "" },
    amenities: [],
    menu: [{ type: String, required: false, trim: true, default: "" }],
    lmenu: [{ type: String, required: false, trim: true, default: "" }],
    totalRooms: { type: String, required: false, trim: true, default: "0" },
    totalBanquet: { type: String, required: false, trim: true, default: "0" },
    priority: {
      type: Number,
      required: false,
      trim: true,
      default: 10,
      enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
    totalLawns: { type: String, required: false, trim: true, default: "0" },
    vegPerPlate: { type: String, required: false, trim: true, default: "0" },
    nonVegPerPlate: { type: String, required: false, trim: true, default: "0" },
    allowedVendors: [],
    features: [],
    secondNumbers: [{ type: String, required: false, trim: true, default: "" }],
    plans: [],
    termsandconditions: {
      type: String,
      required: false,

      trim: true,
      default: "",
    },
    brochure: [{ type: String, required: false, trim: true, default: "" }],
    images: [{ type: String, default: "", trim: "" }],
    vidLinks: [],
    albums: [],
    popular: { type: Boolean, required: false, trim: true, default: false },
    fourStar: { type: Boolean, required: false, trim: true, default: false },
    fiveStar: { type: Boolean, required: false, trim: true, default: false },
    awarded: { type: Boolean, required: false, trim: true, default: false },
    exclusive: { type: Boolean, required: false, trim: true, default: false },
    avgRating: { type: Number, default: 0, trim: "" },
    avgRatingTotalStars: { type: Number, default: 0, trim: "" },
    avgRatingTotalRates: { type: Number, default: 0, trim: "" },
    password: { type: String, required: false, trim: true, default: "" },
    is_approved: { type: Boolean, required: false, trim: true, default: false },
    is_delete: { type: Boolean, required: false, trim: true, default: false },
    is_email_verified: {
      type: Boolean,
      required: false,
      trim: true,
      default: false,
    },
    is_mobile_verified: {
      type: Boolean,
      required: false,
      trim: true,
      default: false,
    },
  },
  { timestamps: true, toObject: { virtuals: true }, toJSON: { virtuals: true } }
);
const VenueUserModels =
  mongoose.models.VenueUser || mongoose.model("VenueUser", VenueUserSchema);

export default VenueUserModels;
